'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class UNICOMEREntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=UNICOMEREntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property COLOR() As DbSet(Of COLOR)
    Public Overridable Property MATERIAL() As DbSet(Of MATERIAL)
    Public Overridable Property MODEL() As DbSet(Of MODEL)
    Public Overridable Property POLICY() As DbSet(Of POLICY)
    Public Overridable Property PRODUCT() As DbSet(Of PRODUCT)
    Public Overridable Property STORE() As DbSet(Of STORE)
    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagrams)
    Public Overridable Property TRANSACTION_TYPE() As DbSet(Of TRANSACTION_TYPE)
    Public Overridable Property UPC() As DbSet(Of UPC)
    Public Overridable Property vwProduct() As DbSet(Of vwProduct)

End Class
