'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PRODUCT
    Public Property ProductId As Integer
    Public Property IdStoreLoadProduct As Nullable(Of Integer)
    Public Property IdStoreDownLoadProduct As Nullable(Of Integer)
    Public Property IdColor As Nullable(Of Integer)
    Public Property IdMaterial As Nullable(Of Integer)
    Public Property IdPolicy As Nullable(Of Integer)
    Public Property IdTransactionType As Nullable(Of Integer)
    Public Property IdUpc As Nullable(Of Integer)
    Public Property IdModel As Nullable(Of Integer)
    Public Property InsertDate As Date
    Public Property UserInsert As Nullable(Of Integer)

    Public Overridable Property COLOR As COLOR
    Public Overridable Property MATERIAL As MATERIAL
    Public Overridable Property MODEL As MODEL
    Public Overridable Property POLICY As POLICY
    Public Overridable Property STORE As STORE
    Public Overridable Property STORE1 As STORE
    Public Overridable Property TRANSACTION_TYPE As TRANSACTION_TYPE
    Public Overridable Property UPC As UPC

End Class
