'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class STORE
    Public Property IdStore As Integer
    Public Property Name As String
    Public Property Direction As String
    Public Property phone1 As String
    Public Property phone2 As String
    Public Property InsertDate As Date

    Public Overridable Property PRODUCT As ICollection(Of PRODUCT) = New HashSet(Of PRODUCT)
    Public Overridable Property PRODUCT1 As ICollection(Of PRODUCT) = New HashSet(Of PRODUCT)

End Class
