'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class UPC
    Public Property IdUpc As Integer
    Public Property UPC1 As String
    Public Property Description As String
    Public Property InsertDate As Date
    Public Property UserInsert As Nullable(Of Integer)
    Public Property IdPolicy As Nullable(Of Integer)

    Public Overridable Property PRODUCT As ICollection(Of PRODUCT) = New HashSet(Of PRODUCT)

End Class
