'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vwProduct
    Public Property ESTADOTRANSACCION As String
    Public Property UPC As String
    Public Property TIENDA_CARGOPRODINICIALMENTE As String
    Public Property TIENDA_MOVIOPRODUCTO As String

End Class
